config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index 
    @pokemons = Pokemon.all
  end 

  def show
    @pokemon = Pokemon.find(params[:id])
  end 

  def new
    @pokemon = Pokemon.new
  end 

  def create 
    @pokemon = Pokemon.create(pokemon_params)

    redirect_to pokemons_path
  end 

  def edit 
    @pokemon = Pokemon.find(params[:id])
  end 

  def update
    @pokemon = Pokemon.find(params[:id])
    @pokemon.update(pokemon_params)

    redirect_to pokemons_path
  end 

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    redirect_to pokemons_path
  end 

private 

  def pokemon_params
    params.require(:pokemon).permit(:name, :weight, :description)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/edit.html.erb
<h1> You found a rare candy! Time to evolve! </h1>

<p><%= form_for @pokemon do |f| %>

    <%= f.label :name  %>
    <%= f.text_field :name %>

    <%= f.label :weight %>
    <%= f.number_field :weight %>

    <%= f.label :description %>
    <%= f.text_field :description %>

  <%= f.submit "Evolve!" %>

  <% end %>

app/views/pokemons/index.html.erb
<h1>Gotta catch 'em all</h1>

<ul>
  <% @pokemons.each do |pokemon| %>
  <li><%= link_to pokemon.name, pokemon %></li>
  <% end %>
</ul>

<h4>I want to...</h4>
<ul>
<li><%= link_to "Create my own", "/pokemons/new" %></li>

</ul>

app/views/pokemons/new.html.erb
<h1>Make your own Pokemon!</h1>


<%= form_for @pokemon do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :weight %>
  <%= f.number_field :weight %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Pokemon!" %>

<% end %>

app/views/pokemons/show.html.erb
<h1>I love this one</h1>

<ul>
<p>Name: <%= @pokemon.name %></p>
<p>Weight: <%= @pokemon.weight %></p>
<p>Type: <%= @pokemon.description %></p>
</ul>

<%= link_to "I want to go back", pokemons_path %>

<%= link_to 'I want to evolve my Pokemon', edit_pokemon_path(@pokemon) %> 
<%= button_to 'I want to pull a team rocket and DESTROY THIS POKEMON', @pokemon, method: :delete, data: { confirm: 'Are you sure?' } %>